"""
Markdown report generator.

Renders the annual report from a Jinja-like template with metrics
and chart references.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)


def _fmt_table(df: pd.DataFrame, max_rows: int = 30) -> str:
    """Convert a DataFrame to a markdown table."""
    if df.empty:
        return "*No data available.*\n"
    return df.head(max_rows).to_markdown(index=False) + "\n"


def generate_report(
    master: pd.DataFrame,
    metrics: dict[str, pd.DataFrame],
    degradation: dict,
    year: int,
    output_dir: Path,
    template_path: Path | None = None,
) -> Path:
    """
    Generate the annual markdown report.

    If a template is provided, it will be used as the base. Otherwise,
    a built-in structure is used.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"annual_report_{year}.md"

    headline = metrics.get("headline", pd.DataFrame())
    h = headline.iloc[0].to_dict() if len(headline) > 0 else {}

    leed_by_grade = metrics.get("leed_by_grade", pd.DataFrame())
    level_by_grade = metrics.get("leed_level_by_grade", pd.DataFrame())
    ll97_summary = metrics.get("ll97_overage_summary", pd.DataFrame())
    match_stats = metrics.get("match_coverage_stats", pd.DataFrame())

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    report = f"""# LEED vs NYC Energy Grades & LL97 — Annual Report {year}

*Generated: {generated_at}*

---

## Executive Summary

This report compares **LEED-certified buildings in New York City** against NYC's
energy performance grades (Local Law 33) and emissions compliance data (Local Law 97).

| Metric | Value |
|--------|-------|
| Total LEED buildings analyzed | {h.get('total_leed_buildings', 'N/A')} |
| Matched to NYC energy grades | {h.get('matched_with_grade', 'N/A')} ({h.get('match_rate_pct', 'N/A')}%) |
| Grade C or D | {h.get('count_grade_c_or_d', 'N/A')} ({h.get('pct_grade_c_or_d', 'N/A')}%) |
| LEED buildings with LL97 data | {h.get('leed_with_ll97_data', 'N/A')} |
| Above LL97 emissions limit | {h.get('count_above_ll97_limit', 'N/A')} ({h.get('pct_above_ll97_limit', 'N/A')}%) |

---

## 1. Energy Grade Distribution

How do LEED-certified buildings perform on NYC's letter grade system?

![Grade Distribution](grade_distribution_{year}.png)

{_fmt_table(leed_by_grade)}

---

## 2. Grade by LEED Certification Level

Does a higher LEED certification level correlate with better energy grades?

![Grade by LEED Level](grade_by_leed_level_{year}.png)

{_fmt_table(level_by_grade)}

---

## 3. LL97 Emissions Compliance

Are LEED buildings meeting NYC's Local Law 97 emissions limits?

![LL97 Overage Histogram](ll97_overage_hist_{year}.png)

{_fmt_table(ll97_summary)}

---

## 4. Operational Degradation

Does energy performance degrade as LEED certifications age?

![Grade vs Certification Age](grade_vs_cert_age_{year}.png)

**Correlation analysis:**
- Pearson correlation (cert age vs grade): **{degradation.get('correlation', 'N/A')}**
- Sample size: {degradation.get('n', 'N/A')}
- Note: {degradation.get('note', '')}

---

## 5. Match Quality

How reliable is the building matching between datasets?

![Match Confidence](match_confidence_breakdown_{year}.png)

{_fmt_table(match_stats)}

---

## Methodology

- LEED data sourced from USGBC Project Directory
- NYC energy grades from LL33 disclosure (NYC Open Data)
- NYC benchmarking from LL84 disclosure (NYC Open Data)
- LL97 emissions data from NYC Open Data
- Building matching uses BBL/BIN IDs, exact address, fuzzy address (rapidfuzz),
  and fuzzy name matching with confidence scoring
- See `docs/methodology.md` for full details

## Limitations

- Match coverage depends on data overlap between LEED and NYC datasets
- Some LEED buildings may not appear in NYC datasets (e.g., below size thresholds)
- Energy grades reflect a single reporting year; LEED certification is point-in-time
- LL97 limits change over compliance periods

---

*Report generated by the LEED vs NYC Energy Grades & LL97 pipeline.*
*See docs/methodology.md and docs/data_dictionary.md for details.*
"""

    report_path.write_text(report)
    logger.info("Report written to %s", report_path)
    return report_path
